[env:motor_esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/tty.SLAB_USBtoUART
lib_deps =
  teemuatlut/TMCStepper@^0.7.3
src_filter = +<motor> -<sensor_ui>

; [env:sensor_ui_esp32]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
; upload_port = /dev/tty.SLAB_USBtoUART
; lib_deps =
; src_filter = +<sensor_ui> -<motor>
